#!/bin/bash
#$ -cwd -V -N mpp_casestudy -e output_files/logs/error-$JOB_NAME-$JOB_ID -o output_files/logs/$JOB_NAME-$JOB_ID
#
#  This is a template submission script for MPI batch jobs on ness,
#  called "mpibatch.sge". The batch system is Sun Grid Engine (SGE).
#
#  ** You do not need to change the contents of this file.           **
#  ** You must simply ensure that it has the correct name.           **
#  ** You can delete lines beginning '#' EXCEPT the first two lines. **
#
#  To submit an executable called "program" you should take a copy
#  of this file and call the copy "program.sge", ie type:
#
#    cp mpibatch.sge program.sge
#
#  To run, for example, using 4 processes you should then type:
#
#    qsub -pe mpi 4 program.sge
#
#  The executable "program" will then be run on 4 processes, and all
#  relevant output will be send to a file called "program.sge.oXXXXX"
#  where XXXXX is the job identifier assigned by SGE. There will be
#  three other files (extensions .e, .po and .pe) which you can ignore.
# 
#  Flags:
#         -pe mpi n:  This is an MPI job requiring n processes, so run
#                     it under the "mpi" Programming Environment (PE).
#
#  Timing information from the unix "time" command will also be appended.
#  Most important is the "real" time which is the elapsed wallclock time.
#

MPIEXE=casestudy

if [[ x$1x == xCOMx ]]; then
echo "--------------------------------------------------"
echo "Running MPI program <$MPIEXE> on" $NSLOTS "processes"
echo "--------------------------------------------------"
echo
pwd
make
pwd
cd bin
(time mpiexec -n $NSLOTS ./$MPIEXE) 2>&1

echo
echo "--------------------"
echo "Finished MPI program"
echo "--------------------"
echo
else
	qsub -pe mpi 4 $0 COM
fi
