#!/bin/bash
#$ -cwd -V -N mpp_cw -e output_files/logs/error-$JOB_NAME-$JOB_ID -o output_files/logs/$JOB_NAME-$JOB_ID

ITERATIONS=100
INPUT_FOLDER=../input_files
INPUT_FILE=edge512x384.pgm
OUTPUT_FOLDER=../output_files
SERIAL="./serial $ITERATIONS $INPUT_FOLDER $INPUT_FILE $OUTPUT_FOLDER"
PARALLEL="./parallel $ITERATIONS $INPUT_FOLDER $INPUT_FILE $OUTPUT_FOLDER"

if [[ x$1x == xCOMx ]]; then
make
cd bin
	echo "#$INPUT_FILE -- $ITERATIONS"
	echo "#SERIAL"
	
  echo -e "#iterations\treal\tuser\tsys"
	echo 0 $((time $SERIAL) )  | awk '/iterations/{printf $1"\t"; gsub( /s/, "", $0 ); gsub ( /m/, " ", $0); printf $16*60+$17"\t" $19*60+$20"\t"$22*60+$23"\n";}'
	echo
	echo "#PARALLEL"
	for N in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16; do
		echo $N $((time mpiexec -n $N $PARALLEL) ) | awk '/iterations/{printf $1"\t"; gsub( /s/, "", $0 ); gsub ( /m/, " ", $0); printf $16*60+$17"\t" $19*60+$20"\t"$22*60+$23"\n";}'
	done
cd ../output_files

	for N in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16; do
		if [[ $(diff $INPUT_FILE\_reconstruct\_p$N\_i$ITERATIONS.pgm $INPUT_FILE\_reconstruct\_serial\_i$ITERATIONS.pgm) ]]; then
			echo "#ERROR IN $N"
		fi
	done 
else
	qsub -pe mpi 16 $0 COM
fi
